
const RECOGNITION_END = "VOICE_RECOGNITION_END";
const RECOGNITION_START = "VOICE_RECOGNITION_START";
const RECOGNITION_UPDATE = "VOICE_RECOGNITION_UPDATE";

export {
  RECOGNITION_END,
  RECOGNITION_START,
  RECOGNITION_UPDATE,
};
